default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: dabrickashaw
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: dkdfs_development

test:
  <<: *default
  database: dkdfs_test

production:
  <<: *default
  database: dkdfs_production
